# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNmED2pr99odFUSjL8Eb0meimcX1HCAn
"""

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1dquaV8RSPu7PslK5Up9kUSmcsYWZH6N2'})
downloaded.GetContentFile('FoodBalanceSheets_E_Africa_NOFLAG.csv')

import pandas as pd

df= pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding= "latin-1")

print(df)

column= df.groupby(['Y2017','Element'])

df.groupby(['Area']).sum()

df.groupby(['Item']).sum()

df.shape

df.groupby(['Y2017','Area']).sum()

missing = df.isnull().sum()

print(missing)

df.corr(Element_Code, Item_Code, Area_Code)

import numpy as np

array  = ([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])

print(array)

S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

df.groupby(['Y2017','Area']).sum()

df.groupby(['Element']).sum()

my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

df.groupby(['Y2017']).sum()

def mean(-1582.0, -1200.0, -1159.0, -865.0, -860.0, 96443.0, 106400.0, 112625.0, 117702.0, 190873)